/**
 * Quotes – curated list for the quotes panel.
 * Add or edit entries; each is { text: string, author: string }.
 */
window.QUOTES = [
    { text: 'the unexamined life is not worth living.', author: 'socrates' },
    { text: 'we are what we repeatedly do. excellence, then, is not an act, but a habit.', author: 'aristotle' },
    { text: 'the only true wisdom is in knowing you know nothing.', author: 'socrates' },
    { text: 'it is not that we have a short time to live, but that we waste a lot of it.', author: 'seneca' },
    { text: 'happiness is not something ready made. it comes from your own actions.', author: 'dalai lama xiv' },
    { text: 'life must be understood backward. but it must be lived forward.', author: 'søren kierkegaard' },
    { text: 'to live is to suffer, to survive is to find some meaning in the suffering.', author: 'friedrich nietzsche' },
    { text: 'the mind is everything. what you think you become.', author: 'buddha' },
    { text: 'we have two lives, and the second begins when we realize we only have one.', author: 'confucius' },
    { text: 'knowing others is intelligence; knowing yourself is true wisdom.', author: 'lao tzu' },
    { text: 'the function of freedom is to free someone else.', author: 'toni morrison' },
    { text: 'even a happy life cannot be without a measure of darkness.', author: 'carl jung' },
    { text: 'what we think, we become.', author: 'often attributed to buddha' },
    { text: 'the cave you fear to enter holds the treasure you seek.', author: 'joseph campbell' },
    { text: 'man is condemned to be free.', author: 'jean-paul sartre' },
    { text: 'one cannot step twice in the same river.', author: 'heraclitus' },
    { text: 'the price of anything is the amount of life you exchange for it.', author: 'henry david thoreau' },
    { text: 'we suffer more often in imagination than in reality.', author: 'seneca' },
    { text: 'luck is what happens when preparation meets opportunity.', author: 'seneca' },
    { text: 'as is a tale, so is life: not how long it is, but how good it is, is what matters.', author: 'seneca' },
    { text: 'we are more often frightened than hurt; and we suffer more from imagination than from reality.', author: 'seneca' },
    { text: 'it is the power of the mind to be unconquerable.', author: 'seneca' },
    { text: 'while we are postponing, life speeds by.', author: 'seneca' },
    { text: 'difficulties strengthen the mind, as labour does the body.', author: 'seneca' },
    { text: 'true happiness is to enjoy the present, without anxious dependence upon the future.', author: 'seneca' },
    { text: 'we learn not in the school, but in life.', author: 'seneca' },
    { text: 'it is not the man who has too little, but the man who craves more, that is poor.', author: 'seneca' },
    { text: 'we are always complaining that our days are few, and acting as though there would be no end of them.', author: 'seneca' },
    { text: 'life is very short and anxious for those who forget the past, neglect the present, and fear the future.', author: 'seneca' },
    { text: 'we are not given a short life but we make it short, and we are not ill-supplied but wasteful of it.', author: 'seneca' },
    { text: 'it does not matter what you bear, but how you bear it.', author: 'seneca' },
    { text: 'begin at once to live, and count each separate day as a separate life.', author: 'seneca' },
    { text: 'a gem cannot be polished without friction, nor a man perfected without trials.', author: 'seneca' },
    // Marcus Aurelius
    { text: 'you have power over your mind—not outside events. realize this, and you will find strength.', author: 'marcus aurelius' },
    { text: 'the happiness of your life depends upon the quality of your thoughts.', author: 'marcus aurelius' },
    { text: 'waste no more time arguing about what a good man should be. be one.', author: 'marcus aurelius' },
    { text: 'when you arise in the morning, think of what a precious privilege it is to be alive.', author: 'marcus aurelius' },
    { text: 'accept the things to which fate binds you, and love the people with whom fate brings you together.', author: 'marcus aurelius' },
    { text: 'the best revenge is not to be like your enemy.', author: 'marcus aurelius' },
    { text: 'it is not death that a man should fear, but he should fear never beginning to live.', author: 'marcus aurelius' },
    { text: 'very little is needed to make a happy life; it is all within yourself.', author: 'marcus aurelius' },
    { text: 'the soul becomes dyed with the colour of its thoughts.', author: 'marcus aurelius' },
    { text: 'loss is nothing else but change, and change is nature\'s delight.', author: 'marcus aurelius' },
    { text: 'think of the life you have lived until now as over and, as a dead man, see what\'s left as a bonus.', author: 'marcus aurelius' },
    { text: 'the object of life is not to be on the side of the majority, but to escape finding oneself in the ranks of the insane.', author: 'marcus aurelius' },
    { text: 'how much more grievous are the consequences of anger than the causes of it.', author: 'marcus aurelius' },
    { text: 'when you have done a good act and another has received it, why do you look for a third thing besides—to pass for a doer of good?', author: 'marcus aurelius' },
    { text: 'look back over the past, with its changing empires that rose and fell, and you can foresee the future too.', author: 'marcus aurelius' },
    { text: 'dwell on the beauty of life. watch the stars, and see yourself running with them.', author: 'marcus aurelius' },
    { text: 'the universe is change; our life is what our thoughts make it.', author: 'marcus aurelius' },
    { text: 'it is in your power to withdraw yourself whenever you desire. perfect tranquillity within consists in the good ordering of the mind.', author: 'marcus aurelius' },
    { text: 'nowhere can man find a quieter or more untroubled retreat than in his own soul.', author: 'marcus aurelius' },
    { text: 'begin each day by telling yourself: today i shall be meeting with interference, ingratitude, arrogance, disloyalty, ill-will, and selfishness.', author: 'marcus aurelius' },
    { text: 'the best answer to anger is silence.', author: 'marcus aurelius' },
    { text: 'confine yourself to the present.', author: 'marcus aurelius' },
    { text: 'remember that very little is needed to make a happy life.', author: 'marcus aurelius' },
    // Psalms
    { text: 'he makes me lie down in green pastures. he leads me beside still waters.', author: 'psalm 23' },
    { text: 'even though i walk through the valley of the shadow of death, i will fear no evil, for you are with me.', author: 'psalm 23' },
    { text: 'the lord is my light and my salvation; whom shall i fear?', author: 'psalm 27' },
    { text: 'wait for the lord; be strong, and let your heart take courage.', author: 'psalm 27' },
    { text: 'be still, and know that i am god.', author: 'psalm 46' },
    { text: 'create in me a clean heart, o god, and renew a right spirit within me.', author: 'psalm 51' },
    { text: 'cast your burden on the lord, and he will sustain you.', author: 'psalm 55' },
    { text: 'this is the day that the lord has made; let us rejoice and be glad in it.', author: 'psalm 118' },
    { text: 'i lift my eyes to the hills. from where does my help come? my help comes from the lord.', author: 'psalm 121' },
    { text: 'the lord will keep your going out and your coming in from this time forth and forevermore.', author: 'psalm 121' },
    { text: 'search me, o god, and know my heart; try me and know my thoughts.', author: 'psalm 139' },
    // St. Paul
    { text: 'for i am convinced that neither death nor life, nor angels nor rulers, nor things present nor things to come, nor powers, nor height nor depth, nor anything else in all creation, will be able to separate us from the love of god.', author: 'st. paul' },
    { text: 'rejoice in the lord always; again i will say, rejoice.', author: 'st. paul' },
    { text: 'do not be anxious about anything, but in everything by prayer and supplication with thanksgiving let your requests be made known to god.', author: 'st. paul' },
    { text: 'and now faith, hope, and love abide, these three; and the greatest of these is love.', author: 'st. paul' },
    { text: 'love is patient and kind; love does not envy or boast; it is not arrogant or rude.', author: 'st. paul' },
    { text: 'for we walk by faith, not by sight.', author: 'st. paul' },
    { text: 'i can do all things through him who strengthens me.', author: 'st. paul' },
    { text: 'for the fruit of the spirit is love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control.', author: 'st. paul' },
    { text: 'let us not grow weary of doing good, for in due season we will reap, if we do not give up.', author: 'st. paul' },
    { text: 'do not be conformed to this world, but be transformed by the renewal of your mind.', author: 'st. paul' },
    { text: 'for we are his workmanship, created in christ jesus for good works.', author: 'st. paul' },
    { text: 'whatever is true, whatever is honorable, whatever is just, whatever is pure, whatever is lovely, whatever is commendable—if there is any excellence, if there is anything worthy of praise, think about these things.', author: 'st. paul' },
    // dr. steinkirch
    { text: 'impossible is a state of mind.', author: 'dr. steinkirch' },
    { text: 'you are supposed to be free.', author: 'dr. steinkirch' },
    { text: 'a man who won\'t defend his woman\'s honor is truly lacking in character.', author: 'dr. steinkirch' },
    { text: 'never understimate (or mess with) someone who has lost everything and has nothing else to lose.', author: 'dr. steinkirch' },
    { text: 'whatever i do now is going to be my best work ever. and whoever i make my family now will be the most loved people ever.', author: 'dr. steinkirch' },
    { text: 'i\'ve spent my entire life building myself into the best mother i could be.', author: 'dr. steinkirch' },
    { text: 'soon i will be sitting in my nice chair, in my nice house, with a nice cup of tea, looking at everything i have and how i overcame so much. and i will feel this immense happiness inside my veins — something so strong and so intense. total. complete. bliss.', author: 'dr. steinkirch' },
    { text: 'being a winner means mastering the art of not taking rejection personally. even better: actively seek it. try everything, reach out to everyone. you\'ll get a flood of NOs and silence. but eventually, a signal breaks through — and when it does, it feels incredible.', author: 'dr. steinkirch' },
    { text: 'being misunderstood is underrated — it\'s a signal that you\'re not following the herd. embrace that feeling, tune out the noise of criticism, and keep trusting your intuition to take you where you need to go.', author: 'dr. steinkirch' },

    // robert greene
    { text: 'no calling is superior to another. what matters is that it be tied to a personal need and inclination, and that your energy moves you toward improvement and continuous learning from experience.', author: 'robert greene' },
    // science
    { text: 'silence is deep as eternity, speech is shallow as time.', author: 'thomas carlyle' },
    { text: 'if our brains were simple, we would be too simple to understand them.', author: 'mario puzo' },
    { text: 'we all agree that your theory is crazy. the question which divides us is whether it is crazy enough.', author: 'niels bohr' },
    { text: 'nothing is great and little otherwise than by comparison.', author: 'jonathan swift' },
    { text: 'when an idea is wanting, a word can always be found to take its place.', author: 'goethe' },
    { text: 'nothing that is worth knowing can be taught.', author: 'oscar wilde' },
    { text: 'the paradox is the source of the thinker\'s passion, and the thinker without a paradox is like a lover without feeling: a paltry mediocrity.', author: 'søren kierkegaard' },
    { text: 'the human understanding is greatly indebted to the passions.', author: 'jean jacques rousseau' },
    { text: 'the real danger is not that computers will begin to think like men, but that men will begin to think like computers.', author: 'sydney j. harris' },
    { text: 'thirty spokes share the wheel\'s hub, but it is the hole in the center that provides its usefulness.', author: 'lao tzu' },
    { text: 'the human race took centuries or millennia to see through the mist of difficulties and paradoxes which instructors now invite us to solve in a few minutes.', author: 'lancelot hogben' },
    { text: 'the attraction of discovering the most elegant way of dividing up the mind into two major complementary cognitive systems is almost irresistible.', author: 'terrence w. deacon' },
    { text: 'learning is, at its base, a function of the probability of correlations between things, from the synaptic level to the behavioral level. past correlations tend to be predictive of future correlations.', author: 'terrence w. deacon' },
    { text: 'a competence is an available skill, normally one learned or acquired previously. so by analogy an innate language competence is an ability to perform certain language tasks as though they had previously been learned.', author: 'terrence w. deacon' },
    { text: 'languages are abstractions. they are fuzzy collections of behaviors that happen to be reasonably well described by logical rule systems.', author: 'terrence w. deacon' },
    { text: 'kind people help each other even without noticing that they are doing so, and evil people act against each other on purpose.', author: 'chinese proverb' },
    { text: 'the history of mankind is the movement of humanity toward greater and greater unification.', author: 'leo tolstoy' },
    { text: 'a gunshot wound may be cured, but the wound made by a tongue never heals.', author: 'persian wisdom' },
    { text: 'i said, i will take heed to my ways, that i sin not with my tongue.', author: 'psalms 39:1' },
    { text: 'abstention should be a habit in your life; it should support you in your virtues. for he who is resolute in goodness, there is nothing that he could not overcome.', author: 'lao-tzu' },
    { text: 'put at least half of your energy into making yourself free of empty wishes, and very soon you will see that in so doing you will receive much greater fulfillment and happiness.', author: 'epictetus' },
    { text: 'god tests everyone, one with wealth, another with poverty. a rich man is tested in whether he would extend an arm of support to those who need it; a poor man in whether he would bear all his sufferings without discontent and with obedience.', author: 'the talmud' },
    { text: 'no matter how many times you aim to achieve victory over your passions, do not give up. every effort weakens the power of passion and makes it easier to gain victory over it.', author: 'leo tolstoy' },
    { text: 'you have to respect every person, no matter how miserable or ridiculous he or she may be. you should remember that in every person lives the same spirit which lives in us.', author: 'arthur schopenhauer' },
    { text: 'pride costs more than all that is necessary for food, drink, shelter, or dress.', author: 'thomas jefferson' },
    { text: 'kindness enriches our life; with kindness mysterious things become clear, difficult things become easy, and dull things become cheerful.', author: 'leo tolstoy' },
    { text: 'a man who starts to live for his soul is like a man who brings a lantern into a dark house. the darkness disappears at once. you have to be persistent in this, and your soul will have this light.', author: 'buddha' },
    { text: 'a constant flow of thoughts expressed by other people can stop and deaden your own thought and your own initiative.', author: 'schopenhauer' },
    { text: 'as we bring up our children, we have to remember that we are caretakers of the future. by improving their education, we improve the future of mankind, the future of this world.', author: 'immanuel kant' },
    { text: 'i think that the major obligation of parents and educators is to give children an understanding of the divine beginning that exists within them.', author: 'william ellery channing' },
    { text: 'when an arrow does not hit its target, the marksman blames himself, not another person. a wise man behaves in the same way.', author: 'confucius' },
    { text: 'faith is the understanding of the meaning of life and the acceptance of those duties and responsibilities connected to it.', author: 'leo tolstoy' },
    { text: 'god is love. and he who lives in love, lives in god, and god lives in him. if we love one another, god lives in us.', author: '1 john, chapter 4' },
    { text: 'love is not a source, it is a consequence of our understanding the divine, spiritual beginning which exists in all of us.', author: 'leo tolstoy' },
    { text: 'improve your own soul, and be confident that only in so doing can you contribute to the improvement of the larger society of which you are part.', author: 'leo tolstoy' },
    { text: 'society can be improved only by self-sacrifice.', author: 'leo tolstoy' },
    { text: 'heaven and earth are eternal because they do not exist for themselves. in the same way, a truly holy person does not live for himself, and therefore he can become eternal, and can achieve anything.', author: 'lao-tzu' },
    { text: 'do not be embarrassed by your mistakes. nothing can teach us better than our understanding of them. this is one of the best ways of self-education.', author: 'thomas carlyle' },
    { text: 'rage is very harmful for all people, but it is most harmful for the man who experiences it.', author: 'leo tolstoy' },
    { text: 'your enemy will pay you back with rage, will make you suffer, but the biggest damage to you will be caused by the rage and hatred existing in your heart.', author: 'dhammapada' },
    { text: 'your rage cannot be justified by anything. the reason for your rage is always inside you.', author: 'leo tolstoy' },
    { text: 'nobody knows where the human race is going. the highest wisdom, then, is to know where you should go: toward perfection.', author: 'leo tolstoy' },
    { text: 'divert your gaze from the world of lies. do not trust your feelings. only in yourself, only in your impersonal self, can you find the eternal.', author: 'dhammapada' },
    { text: 'a wise man loves not because he wants to profit from it but because he finds bliss in love itself.', author: 'leo tolstoy' },
    { text: 'do not regret the past. what is the use of regrets? the lie says that you should regret. the truth says you should be filled with love.', author: 'persian wisdom' },
    { text: 'wisdom is knowing the purpose of life, and knowing how to achieve it.', author: 'leo tolstoy' },
    { text: 'you can achieve wisdom in three ways. the first is meditation — the most noble. the second is imitation — the easiest. the third is experience — the most difficult.', author: 'confucius' },
    { text: 'the merit of a man is not in the knowledge he possesses, but in the effort he made to achieve it.', author: 'gotthold ephraim lessing' },
    { text: 'if you want to study yourself — look into the hearts of other people. if you want to study other people — look into your own heart.', author: 'friedrich von schiller' },
    { text: 'your soul is both your judge and your place of sanctuary. your own soul is your highest judge.', author: 'manu' },
    { text: 'you should respond with kindness toward evil done to you, and you will destroy in an evil person that pleasure which he derives from evil.', author: 'leo tolstoy' },
    { text: 'there are two states of human existence: to live without thinking of death, and to live knowing you approach death with every hour of your life.', author: 'leo tolstoy' },
    { text: 'the more you transform your life from the material to the spiritual domain, the less you become afraid of death.', author: 'leo tolstoy' },
    { text: 'the will of god for us is to live in happiness and to take an interest in the lives of others.', author: 'john ruskin' },
    { text: 'love is real only when a person can sacrifice himself for another person.', author: 'leo tolstoy' },
    { text: 'nothing can make our life, or the lives of other people, more beautiful than perpetual kindness.', author: 'leo tolstoy' },
    { text: 'for a wise man, the wealth, the glory, and the rewards of this world are like sweets or empty shells on a road.', author: 'epictetus' },
    { text: 'remember how many things you lost trying to satisfy your former desires. try to tame your present desires.', author: 'leo tolstoy' },
    { text: 'pure perfection can be found only in god; one\'s life consists of becoming closer to god.', author: 'confucius' },
    { text: 'when two people have a dispute, both are to blame.', author: 'leo tolstoy' },
    { text: 'stop blaming other people, and you will feel relief in your soul.', author: 'leo tolstoy' },
    { text: 'to be strong, you have to be like water.', author: 'lao-tzu' },
    { text: 'water does not stay on a mountaintop, but flows into the valley. in the same manner, real virtue stays only with people who are humble.', author: 'the talmud' },
    { text: 'be as you are, as you have to be, and the rest is god\'s business.', author: 'henri amiel' },
    { text: 'if only god is among us, and eternity exists, then everything is different.', author: 'erasmus' },
    { text: 'one of the key questions we face is whether our lives end after death.', author: 'blaise pascal' },
    { text: 'intellect can be enlightened only in a kind person. a person can be kind only when he has an enlightened intellect.', author: 'chinese wisdom' },
    { text: 'simplicity is the consequence of refined emotions.', author: 'jean d\'alembert' },
    { text: 'words can unite people. therefore, try to speak very clearly, and tell only the truth.', author: 'leo tolstoy' },
];
